name: cats_app

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.3.3 <4.0.0'
    dependencies:
      dio: ^5.4.3+1
      get_it: ^7.7.0
      flutter_bloc: ^8.1.5
      hive: ^2.2.3
      hive_flutter: ^1.1.0