name: commons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: